package com.stockdsl.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Strategy Entity - Represents a User's Trading Strategy
 *
 * ============================================================
 * WHAT IS A STRATEGY?
 * ============================================================
 * A Strategy is a set of trading rules written in our DSL language.
 * Users create strategies that define when to buy and sell stocks.
 *
 * Example Strategy (in DSL):
 *   strategy {
 *     config {
 *       capital = 10000
 *       symbols = [AAPL, MSFT]
 *     }
 *     rule {
 *       if rsi(AAPL) < 30 { buy AAPL }
 *       if rsi(AAPL) > 70 { sell AAPL }
 *     }
 *   }
 *
 * This entity stores:
 * - The DSL code (the actual trading rules)
 * - Metadata (name, description)
 * - Link to the user who owns it
 * - Timestamps (created, updated)
 *
 * ============================================================
 * DATABASE TABLE
 * ============================================================
 * Maps to the 'strategies' table:
 *
 * CREATE TABLE strategies (
 *   id          BIGSERIAL PRIMARY KEY,
 *   user_id     BIGINT NOT NULL REFERENCES users(id),
 *   name        VARCHAR(255) NOT NULL,
 *   description TEXT,
 *   dsl_code    TEXT NOT NULL,
 *   is_public   BOOLEAN DEFAULT FALSE,
 *   created_at  TIMESTAMP,
 *   updated_at  TIMESTAMP
 * );
 *
 * ============================================================
 * RELATIONSHIPS
 * ============================================================
 * - MANY strategies belong to ONE user (Many-to-One)
 *   Each strategy has exactly one owner.
 *
 * - ONE strategy has MANY backtests (One-to-Many)
 *   A strategy can be backtested multiple times.
 */
@Entity                       // JPA: This class maps to a database table
@Table(name = "strategies")   // Maps to the 'strategies' table
@Data                         // Lombok: generates getters/setters
@NoArgsConstructor            // Lombok: generates Strategy() constructor
@AllArgsConstructor           // Lombok: generates all-args constructor
public class Strategy {

    // ==========================================
    // PRIMARY KEY
    // ==========================================

    /**
     * Unique identifier for this strategy.
     *
     * Auto-generated by PostgreSQL (BIGSERIAL).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // ==========================================
    // RELATIONSHIP: Many-to-One with User
    // ==========================================

    /**
     * The user who owns this strategy.
     *
     * @ManyToOne - Many strategies can belong to one user
     *
     * fetch = FetchType.LAZY
     * - Don't load the User object until we actually need it
     * - Improves performance (we don't always need user data)
     *
     * @JoinColumn - Specifies the foreign key column
     * - name = "user_id": Column in strategies table
     * - nullable = false: Every strategy must have an owner
     *
     * @JsonIgnore - Don't include user details in JSON responses
     * - Prevents circular reference: Strategy → User → Strategy → ...
     * - Also hides user data (email, password hash) from API
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    @JsonIgnore
    private User user;

    // ==========================================
    // STRATEGY DETAILS
    // ==========================================

    /**
     * The name of the strategy (e.g., "AAPL RSI Strategy").
     *
     * This is displayed in the dashboard and strategy list.
     */
    @Column(nullable = false)
    private String name;

    /**
     * Optional description of what the strategy does.
     *
     * columnDefinition = "TEXT" allows long descriptions
     * (VARCHAR has length limits, TEXT does not)
     */
    @Column(columnDefinition = "TEXT")
    private String description;

    /**
     * The actual DSL source code.
     *
     * This is the core of the strategy - the trading rules
     * written in our Domain Specific Language.
     *
     * Example:
     *   strategy {
     *     config { capital = 10000 }
     *     rule { if rsi < 30 { buy AAPL } }
     *   }
     *
     * This code is compiled to Python when running a backtest.
     */
    @Column(name = "dsl_code", nullable = false, columnDefinition = "TEXT")
    private String dslCode;

    /**
     * Whether this strategy is publicly visible.
     *
     * Future feature: Allow users to share strategies.
     * Currently all strategies are private (false).
     */
    @Column(name = "is_public")
    private Boolean isPublic = false;

    // ==========================================
    // TIMESTAMPS
    // ==========================================

    /**
     * When this strategy was created.
     * Automatically set when first saved (see @PrePersist).
     */
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    /**
     * When this strategy was last updated.
     * Automatically updated on every save (see @PreUpdate).
     */
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    // ==========================================
    // LIFECYCLE CALLBACKS
    // ==========================================

    /**
     * Set timestamps when strategy is first created.
     *
     * @PrePersist runs BEFORE the first INSERT into the database.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    /**
     * Update timestamp when strategy is modified.
     *
     * @PreUpdate runs BEFORE every UPDATE to the database.
     */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    // ==========================================
    // MANUAL GETTERS AND SETTERS
    // ==========================================
    // Backup in case Lombok isn't working properly.

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public User getUser() { return user; }
    public void setUser(User user) { this.user = user; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public String getDslCode() { return dslCode; }
    public void setDslCode(String dslCode) { this.dslCode = dslCode; }

    public Boolean getIsPublic() { return isPublic; }
    public void setIsPublic(Boolean isPublic) { this.isPublic = isPublic; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    public LocalDateTime getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; }
}
